_wandb:
    value:
        cli_version: 0.21.2
        e:
            sckf49p9k56ckrd65cxxa7q8bgy8pmxm:
                args:
                    - --clientappio-api-address
                    - 127.0.0.1:9094
                    - --parent-pid
                    - "7"
                    - --insecure
                    - --run-once
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "51835101184"
                        used: "17386799104"
                executable: /opt/conda/bin/python
                host: fd-07
                memory:
                    total: "33652133888"
                os: Linux-6.8.0-59-generic-x86_64-with-glibc2.35
                program: /opt/conda/bin/flwr-clientapp
                python: CPython 3.10.13
                root: /app
                startedAt: "2025-08-30T10:53:17.849979Z"
                writerId: sckf49p9k56ckrd65cxxa7q8bgy8pmxm
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 13
                - 14
                - 15
                - 16
            "4": 3.10.13
            "5": 0.21.2
            "10":
                - 20
            "12": 0.21.2
            "13": linux-x86_64
client_name:
    value: EXP_091_N8_R4_E5_CLIENT_02
experiment_id:
    value: 91
hostname:
    value: fd-07
local_epochs:
    value: 5
nodes:
    value: 8
partition_id:
    value: 7
server_rounds:
    value: 4
total_partitions:
    value: 8
