_wandb:
    value:
        cli_version: 0.21.2
        e:
            fy1g4phbrwcke8tmcgusogfjo53w3ouh:
                args:
                    - --clientappio-api-address
                    - 127.0.0.1:9094
                    - --parent-pid
                    - "7"
                    - --insecure
                    - --run-once
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "51835101184"
                        used: "18471677952"
                executable: /opt/conda/bin/python
                host: fd-03
                memory:
                    total: "33652113408"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /opt/conda/bin/flwr-clientapp
                python: CPython 3.10.13
                root: /app
                startedAt: "2025-08-30T09:10:17.922572Z"
                writerId: fy1g4phbrwcke8tmcgusogfjo53w3ouh
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
            "4": 3.10.13
            "5": 0.21.2
            "10":
                - 20
            "12": 0.21.2
            "13": linux-x86_64
client_name:
    value: EXP_079_N6_R4_E2_CLIENT_04
experiment_id:
    value: 79
hostname:
    value: fd-03
local_epochs:
    value: 2
nodes:
    value: 6
partition_id:
    value: 3
server_rounds:
    value: 4
total_partitions:
    value: 6
