_wandb:
    value:
        cli_version: 0.21.1
        e:
            ejt57ronqrdb03qjrgolq6gagbl40pga:
                args:
                    - --clientappio-api-address
                    - 127.0.0.1:9094
                    - --parent-pid
                    - "7"
                    - --insecure
                    - --run-once
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "51835101184"
                        used: "17393119232"
                executable: /opt/conda/bin/python
                host: fd-08
                memory:
                    total: "33652117504"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /opt/conda/bin/flwr-clientapp
                python: CPython 3.10.13
                root: /app
                startedAt: "2025-08-29T15:11:54.062409Z"
                writerId: ejt57ronqrdb03qjrgolq6gagbl40pga
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 5
                - 13
                - 14
                - 15
                - 16
            "4": 3.10.13
            "5": 0.21.1
            "10":
                - 20
            "12": 0.21.1
            "13": linux-x86_64
client_name:
    value: EXP_067_N12_R3_E3_CLIENT_02
experiment_id:
    value: 67
hostname:
    value: fd-08
local_epochs:
    value: 3
nodes:
    value: 12
partition_id:
    value: 8
server_rounds:
    value: 3
total_partitions:
    value: 12
