_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
                - 55
            "3":
                - 2
                - 5
                - 13
                - 14
                - 15
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.13
            "5": 0.19.11
            "8":
                - 5
                - 9
            "10":
                - 20
            "12": 0.19.11
            "13": linux-x86_64
description:
    value: 'Federated Learning: 2 nodi, 3 round, 3 epoche locali'
experiment_id:
    value: 3
hostname:
    value: fd-01
local_epochs:
    value: "3"
nodes:
    value: "2"
server_rounds:
    value: "3"
