_wandb:
    value:
        cli_version: 0.21.2
        e:
            nw33z7ql4ovbocm2oasao0pji9l2ey3y:
                args:
                    - --clientappio-api-address
                    - 127.0.0.1:9094
                    - --parent-pid
                    - "7"
                    - --insecure
                    - --run-once
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "51835101184"
                        used: "18458173440"
                executable: /opt/conda/bin/python
                host: fd-04
                memory:
                    total: "33652129792"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /opt/conda/bin/flwr-clientapp
                python: CPython 3.10.13
                root: /app
                startedAt: "2025-08-30T08:51:23.713564Z"
                writerId: nw33z7ql4ovbocm2oasao0pji9l2ey3y
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 2
                - 5
                - 13
                - 14
                - 15
                - 16
                - 62
            "4": 3.10.13
            "5": 0.21.2
            "10":
                - 20
            "12": 0.21.2
            "13": linux-x86_64
client_name:
    value: EXP_078_N6_R3_E2_CLIENT_06
experiment_id:
    value: 78
hostname:
    value: fd-04
local_epochs:
    value: 2
nodes:
    value: 6
partition_id:
    value: 4
server_rounds:
    value: 3
total_partitions:
    value: 6
