_wandb:
    value:
        cli_version: 0.21.2
        e:
            1syp4c585kqephz6f2elob4ali1j9abx:
                args:
                    - --clientappio-api-address
                    - 127.0.0.1:9094
                    - --parent-pid
                    - "7"
                    - --insecure
                    - --run-once
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "51835101184"
                        used: "18229395456"
                executable: /opt/conda/bin/python
                host: fd-10
                memory:
                    total: "33652125696"
                os: Linux-6.8.0-58-generic-x86_64-with-glibc2.35
                program: /opt/conda/bin/flwr-clientapp
                python: CPython 3.10.13
                root: /app
                startedAt: "2025-08-29T18:10:50.124951Z"
                writerId: 1syp4c585kqephz6f2elob4ali1j9abx
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
            "4": 3.10.13
            "5": 0.21.2
            "10":
                - 20
            "12": 0.21.2
            "13": linux-x86_64
client_name:
    value: EXP_077_N12_R3_E3_CLIENT_10
experiment_id:
    value: 77
hostname:
    value: fd-10
local_epochs:
    value: 3
nodes:
    value: 12
partition_id:
    value: 10
server_rounds:
    value: 3
total_partitions:
    value: 12
