_wandb:
    value:
        cli_version: 0.21.2
        e:
            wn0tt9t15cs3ltbhm1bl69u5zp2ag933:
                args:
                    - --clientappio-api-address
                    - 127.0.0.1:9094
                    - --parent-pid
                    - "7"
                    - --insecure
                    - --run-once
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "51835101184"
                        used: "17396330496"
                executable: /opt/conda/bin/python
                host: fd-07
                memory:
                    total: "33652133888"
                os: Linux-6.8.0-59-generic-x86_64-with-glibc2.35
                program: /opt/conda/bin/flwr-clientapp
                python: CPython 3.10.13
                root: /app
                startedAt: "2025-09-06T09:37:06.670620Z"
                writerId: wn0tt9t15cs3ltbhm1bl69u5zp2ag933
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 2
                - 5
                - 13
                - 14
                - 15
                - 16
                - 62
            "4": 3.10.13
            "5": 0.21.2
            "10":
                - 20
            "12": 0.21.2
            "13": linux-x86_64
client_name:
    value: EXP_111_N8_R5_E4_CLIENT_07
experiment_id:
    value: 111
hostname:
    value: fd-07
local_epochs:
    value: 4
nodes:
    value: 8
partition_id:
    value: 7
server_rounds:
    value: 5
total_partitions:
    value: 8
