_wandb:
    value:
        cli_version: 0.21.2
        e:
            ap5372y4b2t3epptkbpzbpq1zcsit20a:
                args:
                    - --clientappio-api-address
                    - 127.0.0.1:9094
                    - --parent-pid
                    - "7"
                    - --insecure
                    - --run-once
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "51835101184"
                        used: "18458685440"
                executable: /opt/conda/bin/python
                host: fd-04
                memory:
                    total: "33652129792"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /opt/conda/bin/flwr-clientapp
                python: CPython 3.10.13
                root: /app
                startedAt: "2025-08-30T17:03:19.067312Z"
                writerId: ap5372y4b2t3epptkbpzbpq1zcsit20a
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 2
                - 5
                - 13
                - 14
                - 15
                - 16
                - 62
            "4": 3.10.13
            "5": 0.21.2
            "10":
                - 20
            "12": 0.21.2
            "13": linux-x86_64
client_name:
    value: EXP_103_N8_R4_E3_CLIENT_06
experiment_id:
    value: 103
hostname:
    value: fd-04
local_epochs:
    value: 3
nodes:
    value: 8
partition_id:
    value: 4
server_rounds:
    value: 4
total_partitions:
    value: 8
