_wandb:
    value:
        cli_version: 0.21.1
        e:
            ynsur53p3xoltqbg14o9zqv5gqvg3i26:
                args:
                    - --clientappio-api-address
                    - 127.0.0.1:9094
                    - --parent-pid
                    - "7"
                    - --insecure
                    - --run-once
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "51835101184"
                        used: "17593880576"
                executable: /opt/conda/bin/python
                host: fd-09
                memory:
                    total: "33652121600"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /opt/conda/bin/flwr-clientapp
                python: CPython 3.10.13
                root: /app
                startedAt: "2025-08-29T15:52:04.545283Z"
                writerId: ynsur53p3xoltqbg14o9zqv5gqvg3i26
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 13
                - 14
                - 15
                - 16
            "4": 3.10.13
            "5": 0.21.1
            "10":
                - 20
            "12": 0.21.1
            "13": linux-x86_64
client_name:
    value: EXP_069_N10_R3_E3_CLIENT_08
experiment_id:
    value: 69
hostname:
    value: fd-09
local_epochs:
    value: 3
nodes:
    value: 10
partition_id:
    value: 9
server_rounds:
    value: 3
total_partitions:
    value: 10
