_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
                - 55
            "3":
                - 13
                - 23
                - 24
                - 55
            "4": 3.10.13
            "5": 0.19.10
            "8":
                - 5
                - 9
            "12": 0.19.10
            "13": linux-x86_64
