_wandb:
    value:
        cli_version: 0.21.2
        e:
            d88s1n283d3chf9p5r7n037ksabzt882:
                args:
                    - --clientappio-api-address
                    - 127.0.0.1:9094
                    - --parent-pid
                    - "8"
                    - --insecure
                    - --run-once
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "51835101184"
                        used: "19539267584"
                executable: /opt/conda/bin/python
                host: fd-01
                memory:
                    total: "33652125696"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /opt/conda/bin/flwr-clientapp
                python: CPython 3.10.13
                root: /app
                startedAt: "2025-09-06T09:03:06.167754Z"
                writerId: d88s1n283d3chf9p5r7n037ksabzt882
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
            "3":
                - 13
                - 14
                - 15
                - 16
            "4": 3.10.13
            "5": 0.21.2
            "10":
                - 20
            "12": 0.21.2
            "13": linux-x86_64
client_name:
    value: EXP_110_N8_R5_E4_CLIENT_01
experiment_id:
    value: 110
hostname:
    value: fd-01
local_epochs:
    value: 4
nodes:
    value: 8
partition_id:
    value: 1
server_rounds:
    value: 5
total_partitions:
    value: 8
